<?php
include "Point.php";

class MovablePoint extends Point{
    protected $xSpeed;
    protected $ySpeed;

    public function __construct($x, $y,$xSpeed,$ySpeed)
    {
        $this->x=$x;
        $this->y=$y;
        $this->xSpeed=$xSpeed;
        $this->ySpeed=$ySpeed;
    }
    function getXSpeed(){
        return $this->xSpeed;
    }
    function setXSpeed($xSpeed){
        $this->xSpeed=$xSpeed;
    }
    function getYSpeed(){
        return $this->xSpeed;
    }
    function setYSpeed($ySpeed){
        $this->ySpeed=$ySpeed;
    }
    function setSpeed($xSpeed,$ySpeed){
        $this->xSpeed=$xSpeed;
        $this->ySpeed=$ySpeed;
    }
    function getSpeed()
    {
        return [$this->xSpeed, $this->ySpeed];
    }
    function toString()
    {
        echo parent::toString().',speed=('.$this->xSpeed.','.$this->ySpeed.")"   ; // TODO: Change the autogenerated stub
    }
    function  move(){
        $this->x += $this->xSpeed;
        $this->y += $this->ySpeed;
        return $this;
    }
}
